### PR TITLE
Fix local comparison with lists

### PR DESCRIPTION
**Pull request by santiagocardo**
Fix local comparison with lists

### CODE REVIEW

**Comment by smn** [comment]
yeah this is odd:

```elixir
iex(1)> Expression.parse!("@(answers[cursor] == 18)")
[expression: [[]], text: "(answers[cursor] == 18)"]
iex(2)> Expression.parse!("@(18 == answers[cursor])")
[expression: [==: [literal: 18, key: [atom: "answers", atom: "cursor"]]]]
iex(3)> 
```

**Comment by smn** [comment]
It's parser level problem, not an evaluation problem:
```elixir
iex(8)> Expression.parse!("@(answers[cursor] + 1)") 
[expression: [[]], text: "(answers[cursor] + 1)"]
```
Even a `+` operator fails

**Comment by smn** [comment]
And it's got something to do with the square brackets:

```elixir
iex(10)> Expression.parse!("@(answers + 1)")   
[expression: [+: [atom: "answers", literal: 1]]]
```

**Comment by smn** [comment]
Looks like it was a whitespace issue.
```elixir
Expression.parse!("@(answers[cursor]==18)")
``` 
parsed fine which helped me find the issue

**Comment by santiagocardo** [comment]
> Looks like it was a whitespace issue.
> 
> ```elixir
> Expression.parse!("@(answers[cursor]==18)")
> ```
> 
> parsed fine which helped me find the issue

mmm interesting, that should be fixed by modifying the Nimble Parser definitions, right?

**Comment by smn** [comment]
Yup! It’s fixed now @santiagocardo

**Comment by santiagocardo** [comment]
> Yup! It’s fixed now @santiagocardo

how cool! I think you have to approve it yourself!

**Review by smn — APPROVED** [review]

**Comment by smn** [comment]
Yeah. A bit surprised the CLA assistant is kicking in here, it should ignore the turn.io domain.

**Comment by smn** [comment]
Oh I see now, your commits are from a gmail

**Pull request merged**
